import 'package:get/get.dart';

class Messages implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Amount': 'Amount',
          'Station_online': 'Station online',
          'Station_offline': 'Station offline',
          'January': 'January',
          'February': 'February',
          'March': 'March',
          'April': 'April',
          'May': 'May',
          'June': 'June',
          'July': 'July',
          'August': 'August',
          'September': 'September',
          'October': 'October',
          'November': 'November',
          'December': 'December',
          'Transaction': 'Transaction',
          ' TRX': 'TRX',
          ' EGP': 'EGP',
          'Tips': 'Tips',
          'Total': 'Total',
          'Collecting Config...': 'Collecting Config...',
          'Reading Local Config...': 'Reading Local Config...',
          'OK': 'OK',
          'PUMP': 'PUMP',
          'Pump': 'Pump',
          'Nozzles': 'Nozzles',
          'Pumps_Alert': 'Pumps Alert',
          "click_on_pump_to_know_its_status":
              "click on pump to know it's status",
          'Alert': 'Alert',
          'Sorry_the_pump': 'Sorry, the pump',
          'is_in_progress': 'is in progress',
          'NOZZLE': 'NOZZLE',
          'Nozzle': 'Nozzle',
          'Gasoline 95': 'Gasoline 95',
          'Gasoline 92': 'Gasoline 92',
          'Gasoline 80': 'Gasoline 80',
          'Diesel': 'Diesel',
          'Price': 'Price',
          'Liter': 'Liter',
          'Enter_number': 'Enter number',
          'LTR': 'LTR',
          'Full_Tank': 'Full Tank',
          'EGP': 'EGP',
          'Fueling_in_progress...': 'Fueling in progress...',
          'Give_Tips': 'Give Tips',
          'Enter_Tips_Only': 'Enter Tips Only',
          'Or_Enter_All_Amount': 'Or Enter All Amount',
          'Enter_Total': 'Enter Total',
          'Pay': 'Pay',
          'Total_Amount': 'Total Amount',
          'Cash': 'Cash',
          'Bank_Card': 'Bank Card',
          'Client_Receipt': 'Client Receipt',
          'Station_Name': 'Station Name',
          'Transaction_Seq_No': 'Transaction Seq No',
          'Pump_No': 'Pump No',
          'Nozzle_No': 'Nozzle No',
          'Product_No': 'Product No',
          'Product_Name': 'Product Name',
          'No_product': 'No product ',
          'Payment_Type': 'Payment Type ',
          'Calibration': 'Calibration',
          'Transaction_By': 'Transaction By',
          'Total_Amount_reciept': 'Total Amount',
          'Volume:': 'Volume',
          'Unit_Price:': 'Unit Price ',
          'Total_reciept': 'Total reciept',
          'Print_Receipt': 'Print Receipt ',
          'Total_Paid': 'Total Paid',
          'Thank_you_for_your_visit': 'Thank you for your visit ',
          'Supervisor': 'Supervisor',
          'Start_at': 'Start at ',
          'S/N': 'S/N',
          'Home': 'Home ',
          'Fuels': 'Fuels  ',
          'Telecollect': 'Telecollect ',
          'Force_Login': 'Force Login',
          'Transactions | All': 'Transactions | All',
          'Transactions | Available': 'Transactions | Available',
          'Report | Shifts': 'Report | Shifts',
          'Pump_Calibration': 'Pump Calibration',
          'Close_Shift': 'Close Shift',
          'Arabic': 'Arabic',
          'Report | Transactions': 'Report | Transactions',
          'Nozzles_Status': 'Nozzles Status',
          'All_Nozzles_are_ready_for_fueling':
              'All Nozzles are ready for fueling',
          'Error': 'Error',
          'Pre_sale_value_cannot_be_0_or_empty_or_small_than_10':
              'sale value cannot be 0 or empty or small than 10 or exceed 10000',
          'Amount_Details': 'Amount Details',
          'Payment_Alert': 'Payment Alert',
          'sorry': 'sorry',
          'you_have_to_choose_a_payment_method':
              'you have to choose a payment method',
          'State': 'State',
          'Details': 'Details',
          'Transaction_Details': 'Transaction Details',
          'Start_Date': 'Start Date',
          'T/V': 'T/V',
          'U/P': 'U/P',
          'POS': 'POS',
          'End_Date': 'End Date',
          'Choose_Payment': 'Choose Payment',
          'Bank': 'Bank',
          'Check_Remains': 'Check Remains',
          'Invalid_OTP': 'Invalid OTP',
          'please_try_again': 'please try again',
          'Report_Transactions': 'Report Transactions',
          'Number_of_Transactions': 'Number of Transactions',
          'Total_Tips': 'Total Tips',
          'Totals': 'Totals',
          'Report_shift': 'Report shift',
          'Shift_id': 'Shift id',
          'Start_Shift': 'Start Shift',
          'End_Shift': 'End Shift',
          'Total_Money': 'Total Money',
          'Status': 'Status',
          'AMT': 'AMT',
          'Please_enter_your_full_OTP': 'Please enter your full OTP',
          'You_have_to_be_online_to_start_a_new_shift':
              'You have to be online to start a new shift',
          'You_should_be_online_to_close_shift':
              'You should be online to close shift',
          'Type': 'Type',
          'ecrRefNO': 'ecrRefNO',
          'Tip': 'Tip',
          'Stan': 'Stan',
          'Set_Transaction': 'Set Transaction',
          'complete': 'complete',
          'Bank_Point': 'Bank Point',
          'Bank Point': 'Bank Point',
          'Fleet': 'Fleet',
          'Settlement_trans': 'Transactions | Settlement',
          'Syncing': 'Syncing',
          "opened": 'opened',
          'Not_Closed_until_now': 'Not Closed until now',
          'You_should_pay_transaction_first':
              'You should pay transaction first',
          'You_have_to_pay_the_available_transactions_first':
              'You have to pay the available transactions first',
          'you_can_not_close_the_shift': 'you can not close the shift',
          'there_is_a_pump_in_use': 'there is a pump in use',
          'No_Available_Transactions': 'No Available Transactions',
          'Payable': 'Payable',
          'T/A': 'T/A',
          'Unknown': 'Unknown',
          'closed': 'closed',
          'Validate_Your_Transaction': 'Validate Your Transaction',
          'Product': 'Product',
          'Qty': 'Qty',
          'Day': 'Day',
          'Time': 'Time',
          'Cancel': 'Cancel',
          'Confirm': 'Confirm',
          'AM': 'AM',
          'PM': 'PM',
          'Access_Denied': 'Access Denied',
          'You_do_not_have_permission_to_access_this_transaction':
              'You do not have permission to access this transaction',
          'Connection_Stablished': 'Connection Stablished',
          'POS_Logged_In': 'POS Logged In',
          'Starting_Connection': 'Starting Connection',
          'Connection_Failed': 'Connection Failed',
          'Socket_not_connected': 'Socket not connected',
          'not_correct_Tips': 'not correct Tips',
          'Please_make_sure_the_Tips_amount_is_greater_than_the':
              'Please make sure the Tips amount is greater than the',
          'Fueling_Amount': 'Fueling Amount',
          'Invalid_input': 'Invalid input',
          'Please_enter_a_valid_number': 'Please enter a valid number',
          'Please_ensure_the_Tips_amount_is_greater_than':
              'Please ensure the Tips amount is greater than',
          'Please_enter_your_Amount': 'Please enter your Amount',
          'Incorrect_password': 'Incorrect password',
          'try_again': 'try again',
          'not_correct_Total': 'not correct Total',
          'Please_make_sure_the_total_amount_is_greater_than_the_fueling_amount':
              'Please make sure the total amount is greater than the fueling amount',
          'not_correct_Tips_the_max_tips': 'not correct Tips the max tips',
          'Void': 'Void',
          'Re_print': 'Re-print',
          'voucherNo': 'voucherNo',
          'batchNo': 'batchNo',
          'Confirm_Void_Transaction': 'Confirm Void Transaction',
          'Stannumber_not_found': 'Stannumber not found',
          'Are_you_sure_you_want_to_void_this_transaction_with_Stannumber':
              'Are you sure you want to void this transaction with Stannumber',
          'Submit': 'Submit',
          'Enter_Password': 'Enter Password',
          'Enter_Password_to_Exit': 'Enter Password to Exit',
          'Password': 'Password',
          'and': 'and',
          'Loading': 'Loading',
          'You_are_connected': 'You are already connected',
          'No_Connection': 'No Connection',
          'check_shift': 'click to check shift status',
          'Remains': 'Remains',
          'Close_Pending': 'Close Pending...',
          'Close_Processing': 'Close Processing...',
          'You_have_to_pay_the_void_transactions_first':
              'You have to pay the transactions void first'
        },
        'ar': {
          'Stannumber_not_found': 'لا يوجد ستان',
          'not_correct_Tips_the_max_tips': 'غير صحيح أقصي حد للإكرامية ',
          'Please_make_sure_the_total_amount_is_greater_than_the_fueling_amount':
              'يرجى التأكد من أن المجموع أكبر من  المبلغ',
          'not_correct_Total': 'إجمالي غير صحيح',
          'try_again': 'حاول مرة أخرى',
          'Invalid_input': 'خطأ في الإدخال',
          'Fueling_Amount': 'المبلغ',
          'not_correct_Tips': 'خطأ في الإكرامية',
          'Socket_not_connected': 'غير متصل',
          'Connection_Failed': 'خطأ في الإتصال',
          'Amount': 'الاجمالي',
          'Station_online': 'المحطة متصلة',
          'Station_offline': 'المحطة غير متصلة',
          'January': 'يناير',
          'February': 'فبراير',
          'March': 'مارس',
          'April': 'أبريل',
          'May': 'مايو',
          'June': 'يونيو',
          'July': 'يوليو',
          'August': 'أغسطس',
          'September': 'سيبتمبر',
          'October': 'أكتوبر',
          'November': 'نوفمبر',
          'December': 'ديسمبر',
          'Transaction': 'المعاملات',
          ' TRX': 'معاملة',
          'TRX': 'معاملة',
          ' EGP': ' ج.م ',
          'Tips': 'إكرامية',
          'Total': 'المجموع',
          'Collecting Config...': 'جاري تحميل البيانات',
          'Reading Local Config...': ' جاري قراءة البيانات المخزنة',
          'OK': 'موافق',
          'PUMP': 'مضخة',
          'Pump': 'مضخة',
          'Nozzles': 'مسدس',
          "Pumps_Alert": 'تنبيه المضخات',
          'click_on_pump_to_know_its_status':
              'قم بالضغط علي المضخة لمعرفة حالتها ',
          'Alert': 'تنبية',
          'Sorry_the_pump': 'نأسف المضخة',
          'is_in_progress': 'تحت الاستخدام',
          'NOZZLE': 'المسدس',
          'Nozzle': 'المسدس',
          'Gasoline 95': 'بنزين 95',
          'Gasoline 92': 'بنزين 92',
          'Gasoline 80': 'بنزين 80',
          'Diesel': 'سولار',
          'Price': 'السعر',
          'Liter': ' لتر',
          'Enter_number': 'ادخل الرقم',
          'LTR': 'لتر',
          'Full_Tank': 'تفويلة',
          'EGP': 'ج.م',
          'Fueling_in_progress...': 'جاري تنزيل المنتج .........',
          'Give_Tips': 'امنحني إكرامية ...... ؟ ',
          'Enter_Tips_Only': 'ادخل إكرامية فقط',
          'Or_Enter_All_Amount': 'أو ادخل المبلغ الكلي',
          'Enter_Total': 'إجمالي المبلغ',
          'Pay': 'أدفع',
          'Total_Amount': 'المجموع (الاجمالي + الإكرامية)',
          'Cash': 'نقداً',
          'Bank_Card': 'كارت البنك',
          'Client_Receipt': 'أيصال العميل',
          'Station_Name': 'اسم المحطة',
          'Transaction_Seq_No': 'رقم المعاملة ',
          'Pump_No': 'رقم المضخة',
          'Nozzle_No': 'رقم المسدس',
          'Product_No': 'رقم المنتج',
          'Product_Name': 'اسم المنتج',
          'No_product': 'لا يوجد منتج',
          'Payment_Type': 'طريقة الدفع',
          'Calibration': 'العيار',
          'Transaction_By': 'منفذ العملية',
          'Total_Amount_reciept': 'الاجمالي',
          'Volume:': 'الكمية',
          'Unit_Price:': 'سعر المنتج',
          'Total_reciept': 'المجموع',
          'Print_Receipt': 'طباعة الإيصال',
          'Total_Paid': 'إجمالي المدفوع',
          'Thank_you_for_your_visit': 'شكرا علي زيارتكم',
          'Supervisor': 'المشرف',
          'Start_at': 'بدأ ',
          'S/N': 'سيريال',
          'Home': 'الصفحة الرئيسية',
          'Fuels': 'الدخول الي المضخات',
          'Telecollect': 'تحديث البيانات',
          'Force_Login': 'الاتصال الأجباري',
          'Transactions | All': ' المعاملات | الكل',
          'Transactions | Available': 'المعاملات | المتاحة',
          'Report | Shifts': 'تقرير | الورديّة',
          'Pump_Calibration': 'العيار',
          'Close_Shift': 'غلق الورديّة',
          'Arabic': 'اللغة العربية',
          'Report | Transactions': 'تقرير | المعاملات',
          'Nozzles_Status': 'حالة المسدس',
          'All_Nozzles_are_ready_for_fueling': 'جميع المسدسات جاهزة للوقود',
          'Error': 'خطأ',
          'Pre_sale_value_cannot_be_0_or_empty_or_small_than_10':
              'لا يمكن أن تكون القيمة 0 او فارغة او أقل من 10 أو أكبر من 9999',
          'Amount_Details': 'تفاصيل المعاملة',
          'Payment_Alert': 'تنبيه الدفع ',
          'sorry': 'نأسف',
          'you_have_to_choose_a_payment_method': 'يجب عليك إختيار طريقة الدفع',
          'State': 'حالة',
          'Details': 'تفاصيل',
          'Transaction_Details': 'تفاصيل المعاملة',
          'Start_Date': 'تاريخ البدء',
          'T/V': 'الكمية',
          'U/P': 'اللتر',
          'POS': 'الماكينة',
          'End_Date': 'تاريخ الإنتهاء',
          'Choose_Payment': 'اختار طريقة الدفع',
          'Bank': 'البنك',
          'Check_Remains': 'تأكد من الجميع',
          'Invalid_OTP': 'كود خطأ',
          'please_try_again': 'حاول مرة اخري',
          'Report_Transactions': 'تقرير المعاملات',
          'Number_of_Transactions': 'عدد المعاملات',
          'Total_Tips': 'إجمالي الإكراميات',
          'Totals': 'إجمالي',
          'Report_shift': 'تقرير الورديّة',
          'Shift_id': 'رقم الورديّة',
          'Start_Shift': 'بداية الورديّة',
          'End_Shift': 'نهاية الورديّة',
          'Total_Money': 'إجمالي المبلغ',
          'Status': 'الحالة',
          'AMT': 'مبلغ',
          'Please_enter_your_full_OTP': 'من فضلك أدخل الكود الخاص بك',
          'You_have_to_be_online_to_start_a_new_shift':
              'يجب ان تكون متصل حتي تبدأ الورديّة الجديدة',
          'You_should_be_online_to_close_shift':
              'يجب ان تكون متصل حتي تغلق الورديّة',
          'Type': 'النوع',
          'ecrRefNO': 'رقم المعاملة',
          'Tip': 'الإكرامية',
          'Stan': 'ستان',
          'Set_Transaction': 'دفع المعاملة',
          'complete': 'مدفوع',
          'Bank_Point': 'نقاط البنك',
          'Fleet': 'فليت',
          'Settlement_trans': 'تسوية المعاملات',
          'Syncing': 'الأتصال بالبوّابة الإلكترونيّة',
          'opened': 'مفتوح',
          'Not_Closed_until_now': 'لم يتم الغلق حتي الان',
          'You_should_pay_transaction_first': 'يجب ان تدفع المعاملة اولا',
          'You_have_to_pay_the_available_transactions_first':
              'يجب عليك ان تقوم بدفع المعاملات المتاحة اولا',
          'you_can_not_close_the_shift': 'انت لا تستطيع غلق هذه الوردية',
          'there_is_a_pump_in_use': 'يوجد مضخة مستخدمة',
          'No_Available_Transactions': 'لا يوجد معاملات متاحة',
          'Payable': 'جاهزة للدفع',
          'T/A': 'المبلغ',
          'Unknown': 'غير مُعرفة',
          'closed': 'مغلق',
          'Validate_Your_Transaction': 'التحقق من المعاملة',
          'Product': 'المنتج',
          'Qty': 'كمية',
          'Day': 'يوم',
          'Time': 'وقت',
          'Cancel': 'غلق',
          'Confirm': 'موافقة',
          'AM': 'ص',
          'PM': 'م',
          'Access_Denied': 'غير مسموح بالدخول',
          'You_do_not_have_permission_to_access_this_transaction':
              'ليس لديك إذن للوصول إلى هذه المعاملة',
          'Connection_Stablished': 'تم إنشاء إتصال',
          'POS_Logged_In': 'تم تسجيل دخول الماكينة بنجاح',
          'Starting_Connection': 'محاولة الإتصال',
          'Please_make_sure_the_Tips_amount_is_greater_than_the':
              'يرجى التأكد من أن مبلغ الإكرامية أكبر من',
          'Please_enter_a_valid_number': 'برجاء إدخال رقم صحيح',
          'Please_ensure_the_Tips_amount_is_greater_than':
              'يرجى التأكد من أن مبلغ الإكرامية أكبر من',
          'Please_enter_your_Amount': 'من فضلك أدخل المبلغ',
          'Incorrect_password': 'كلمة السر خطأ',
          'Void': 'إلغاء',
          'Re_print': 'إعادة الطباعة',
          'voucherNo': 'رقم الإيصال',
          'batchNo': 'رقم الدفعة',
          'Confirm_Void_Transaction': 'تأكيد إلغاء المعاملة',
          'Are_you_sure_you_want_to_void_this_transaction_with_Stannumber':
              'هل أنت متأكد من أنك تريد إلغاء هذه المعاملة مع الستان',
          'Bank Point': 'نقاط البنك',
          'Submit': 'تأكيد',
          'Enter_Password': 'إدخل الرقم السري',
          'Enter_Password_to_Exit': 'إدخل الرقم السري للخروج',
          'Password': 'رقم سري',
          'and': 'و',
          'Loading': 'تحميل',
          'You_are_connected': 'أنت مُتصل بالفعل',
          'No_Connection': 'لا يوجد إتصال',
          'check_shift': 'أضغط للتحقق من وجود ورديّة مفتوحة',
          'Remains': 'متبقي',
          'Close_Pending': 'الانتظار لإغلاق الورديّة',
          'Close_Processing': 'إغلاق الورديّة قيد التنفيذ',
          'You_have_to_pay_the_void_transactions_first':
              'يجب أن تدفع المعاملات الملغاة أولا',
        }
      };
}
